title: My Evernote Blog
author: keisoko
email: keisoko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about all things Evernote. "Remember Everything"

# social links
github_username: keisoko

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
